{
    home.file.".background-image".source = ./background-image;
    xdg.configFile."i3/config".text = ''
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

                set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
                font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
                floating_modifier $mod

# start a terminal
                bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
                bindsym $mod+Shift+c kill

# start dmenu (a program launcher)
                bindsym $mod+r exec /run/current-system/sw/bin/dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
                bindsym $mod+Tab focus right
                bindsym $mod+Shift+Tab focus left

# alternatively, you can use the cursor keys:
                bindsym $mod+Left focus left
                bindsym $mod+Down focus down
                bindsym $mod+Up focus up
                bindsym $mod+Right focus right

# move focused window
                bindsym $mod+Shift+j move left
                bindsym $mod+Shift+k move down
                bindsym $mod+Shift+l move up
                bindsym $mod+Shift+m move right

# alternatively, you can use the cursor keys:
                bindsym $mod+Shift+Left move left
                bindsym $mod+Shift+Down move down
                bindsym $mod+Shift+Up move up
                bindsym $mod+Shift+Right move right

# split in horizontal orientation
                bindsym $mod+h split h

# split in vertical orientation
                bindsym $mod+v split v

# enter fullscreen mode for the focused container
                bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
                bindsym $mod+s layout stacking
                bindsym $mod+z layout tabbed
                bindsym $mod+e layout toggle split

# toggle tiling / floating
                bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
                bindsym $mod+space focus mode_toggle

# focus the parent container
                bindsym $mod+q focus parent

# focus the child container
#bindsym $mod+d focus child

                focus_follows_mouse no

# switch to workspace
                bindcode $mod+10 workspace 1
                bindcode $mod+11 workspace 2
                bindcode $mod+12 workspace 3
                bindcode $mod+13 workspace 4
                bindcode $mod+14 workspace 5
                bindcode $mod+15 workspace 6
                bindcode $mod+16 workspace 7
                bindcode $mod+17 workspace 8
                bindcode $mod+18 workspace 9
                bindcode $mod+19 workspace 10

# move focused container to workspace
                bindcode $mod+Shift+10 move container to workspace 1
                bindcode $mod+Shift+11 move container to workspace 2
                bindcode $mod+Shift+12 move container to workspace 3
                bindcode $mod+Shift+13 move container to workspace 4
                bindcode $mod+Shift+14 move container to workspace 5
                bindcode $mod+Shift+15 move container to workspace 6
                bindcode $mod+Shift+16 move container to workspace 7
                bindcode $mod+Shift+17 move container to workspace 8
                bindcode $mod+Shift+18 move container to workspace 9
                bindcode $mod+Shift+19 move container to workspace 10

# reload the configuration file
                bindsym $mod+Shift+a reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
                bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
                bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
                mode "resize" {
# These bindings trigger as soon as you enter the resize mode

# Pressing left will shrink the window’s width.
# Pressing right will grow the window’s width.
# Pressing up will shrink the window’s height.
# Pressing down will grow the window’s height.
                    bindsym j resize shrink width 10 px or 10 ppt
                        bindsym k resize grow height 10 px or 10 ppt
                        bindsym l resize shrink height 10 px or 10 ppt
                        bindsym m resize grow width 10 px or 10 ppt

# same bindings, but for the arrow keys
                        bindsym Left resize shrink width 10 px or 10 ppt
                        bindsym Down resize grow height 10 px or 10 ppt
                        bindsym Up resize shrink height 10 px or 10 ppt
                        bindsym Right resize grow width 10 px or 10 ppt

# back to normal: Enter or Escape
                        bindsym Return mode "default"
                        bindsym Escape mode "default"
                }

            bindsym $mod+d mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
                bar {
                    status_command /run/current-system/sw/bin/i3status
# tray_output primary
                }

            bindsym $mod+l exec i3lock -t -i ~/.background-image

            for_window [window_type=dialog] focus
                '';
}
